<html>
	<head>

		 	<meta charset="utf-8">
		    <meta http-equiv="X-UA-Compatible" content="IE=edge">
		    <meta name="viewport" content="width=device-width, initial-scale=1">
		    <title>Play with Raty</title>

		    <!-- Bootstrap -->
		    <link href="css/bootstrap.min.css" rel="stylesheet">
		    
		    <link rel="stylesheet" href="css/bootstrap.min.css"/>
		    <link rel="stylesheet" href="css/bootstrapValidator.min.css"/>
		    <link rel="stylesheet" href="css/style.css">
		    
		    <script src="js/jquery.min.js"></script>
		    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>  

	</head>
	
	<body>
		
		<form id="ratyForm" method="post" class="form-horizontal">
    			<div class="form-group">
			        <label class="col-lg-3 control-label">Rating</label>
			        <div class="col-lg-5">
            			<div id="ratyRating"></div>
        			</div>
    			</div>

    			<div class="form-group">
				    <label class="col-lg-3 control-label">Review title</label>
				    <div class="col-lg-5">
            			<input type="text" class="form-control" name="title" />
        			</div>
    			</div>

			    <div class="form-group">
			        <label class="col-lg-3 control-label">Your review</label>
			        <div class="col-lg-5">
			            <textarea rows="5" class="form-control" name="content"></textarea>
			        </div>
			    </div>

			    <div class="form-group">
			        <div class="col-lg-5 col-lg-offset-3">
			            <button type="submit" class="btn btn-primary">Validate</button>
			        </div>
			    </div>
		</form>


		<!-- Include Raty JS file -->
		<script src="js/jquery.raty.min.js"></script>
		
		<script>

		$(document).ready(function() {
		    // Raty example
		    $('#ratyRating').raty({
		        path: 'css/star-off',
		        size: 24,
		        // The name of hidden field generated by Raty
		        scoreName: 'star',
		        // Re-validate the star rating whenever user change it
		        click: function (score, evt) {
		            $('#ratyForm')
		                .data('bootstrapValidator')             // Return the bootstrapValidator instance
		                .updateStatus('star', 'NOT_VALIDATED')  // Mark the star field as not validated yet
		                .validateField('star');                 // Validate it again
		        }
		    });
		    $('#ratyForm')
		        .bootstrapValidator({
		            // The disabled elements are excluded
		            // Hidden elements (including the rating star) are included
		            excluded: ':disabled',
		            feedbackIcons: {
		                valid: 'glyphicon glyphicon-ok',
		                invalid: 'glyphicon glyphicon-remove',
		                validating: 'glyphicon glyphicon-refresh'
		            },
		            fields: {
		                star: {
		                    validators: {
		                        notEmpty: {
		                            message: 'The rating is required'
		                        }
		                    }
		                },
		                title: {
		                    validators: {
		                        notEmpty: {
		                            message: 'The review title is required'
		                        }
		                    }
		                },
		                content: {
		                    validators: {
		                        notEmpty: {
		                            message: 'The review content is required'
		                        },
		                        stringLength: {
		                            max: 200,
		                            message: 'The review content must be less than 200 characters'
		                        }
		                    }
		                }
		            }
		        });
		});
		</script>

		<script src="js/bootstrap.min.js"></script>
		<script src="js/bootstrapValidator.min.js"></script>
    	<!-- Include all compiled plugins (below), or include individual files as needed -->

	
	</body>

</html>